const Ownable = artifacts.require('Ownable')
const KittyAccessControl = artifacts.require('KittyAccessControl')
const KittyBase = artifacts.require('KittyBase')
const ERC721Metadata = artifacts.require('ERC721Metadata')
const KittyOwnership = artifacts.require('KittyOwnership')
const KittyBreeding = artifacts.require('KittyBreeding')
const ClockAuctionBase = artifacts.require('ClockAuctionBase')
const Pausable = artifacts.require('Pausable')
const ClockAuction = artifacts.require('ClockAuction')
// const SiringClockAuction = artifacts.require('SiringClockAuction')
// const SaleClockAuction = artifacts.require('SaleClockAuction')
const KittyAuction = artifacts.require('KittyAuction')
const KittyMinting = artifacts.require('KittyMinting')
const KittyCore = artifacts.require('KittyCore')

module.exports = function (deployer) {
  deployer.deploy(Ownable)
  deployer.deploy(KittyAccessControl)
  deployer.deploy(KittyBase)
  deployer.deploy(ERC721Metadata)
  deployer.deploy(KittyOwnership)
  deployer.deploy(KittyBreeding)
  deployer.deploy(ClockAuctionBase)
  deployer.deploy(Pausable)
  deployer.deploy(ClockAuction, '0x998d55E88f7bc323ed01eD3c338c4de0c955c1C3', 50)
  // deployer.deploy(SiringClockAuction)
  // deployer.deploy(SaleClockAuction)
  deployer.deploy(KittyAuction)
  deployer.deploy(KittyMinting)
  deployer.deploy(KittyCore)
}
